### ISSUE TITLE
Generate data in multiple cells?

### ISSUE THREAD

**Issue by zohozer** [karakasa/PancakeSpreadsheet#1]
Hi. Please can you provide a sample on how I can pass the information from Grasshopper tree into "Set Multiple Cells" component because seems that nothing that I tried works.

I do have a list with branches that contains 5 indices like this:

![Pancake_Sheet_create_multiple_cells](https://user-images.githubusercontent.com/5983791/194728077-d19c073f-6b56-4e4b-83f0-863d7fc583ea.PNG)

The 5th element it's a separator. It is a long list and I do need to split in multiple columns to fit an A4 page paper into the xlsx file. Basically I want to create an excel spreadheet to feed all this information and create some labels. 

I want to split the content in three or four colums to fit the content into the cells like in this page template:

![](https://extensions.libreoffice.org/assets/screenshots/z/blank-21-label-template_a4d859c3-232b-4b6f-af00-76260123a327__FitMaxWzEwMDAsMTAwMF0.jpeg)

**Comment by karakasa** [comment]
@zohozer 

If I understand correctly, you want an Excel file like this:

![image](https://user-images.githubusercontent.com/12855165/194734698-9cbccea0-a7df-433d-83cc-744ba7b4ea57.png)

Now there's a bug that `Set Multiple Cells` requires a calculated cell range, i.e., you must specify the entire area to set, instead of the left-top corner only.

[label_gh.zip](https://github.com/karakasa/PancakeSpreadsheet/files/9740665/label_gh.zip)

![1](https://user-images.githubusercontent.com/12855165/194735336-05a17aae-43a4-44e2-8103-e4be37bab830.png)

![image](https://user-images.githubusercontent.com/12855165/194735342-f867bdc4-bc93-458a-840a-716323903846.png)

**Comment by zohozer** [comment]
Thank you very much. Exactly what I needed.
